### ISSUE TITLE
.Net 7 Compatability

### ISSUE THREAD

**Issue by grahamoriley** [paintdotnet/System.Windows.Forms.Legacy#4]
Time Elapsed: 00:00:01.5144042
PM> Install-Package Microsoft.VisualStudio.Web.CodeGeneration.Design
Restoring packages for C:\Software Coding\Netdocs Apps\blazor\apaas_netdocs\apaas_netdocs\apaas_netdocs.csproj...

Install-Package : NU1202: Package **Unofficial.System.Windows.Forms.Legacy 1.0.0 is not compatible with net7.0** (.NETCoreApp,Version=v7.0). Package Unofficial.System.Windows.Forms.Legacy 1.0.0 supports: net6.0-windows7.0 
(.NETCoreApp,Version=v6.0)
At line:1 char:1
+ Install-Package Microsoft.VisualStudio.Web.CodeGeneration.Design
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'apaas_netdocs'.
At line:1 char:1
+ Install-Package Microsoft.VisualStudio.Web.CodeGeneration.Design
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

Is .Net 7 compatability on the roadmap?

Regards,
Graham

**Comment by rickbrew** [comment]
This isn't a .NET 7 compatibility issue, your target framework just isn't specific enough.

The key here is that S.W.F.Legacy is targeting `net6.0-windows`, which means that you can't target just `net7.0`, you must be targeting `net7.0-windows`.
